version: "3.9"
services:
  topic:
    build: .
    image: lintoai/linto-platform-nlp-topic-modeling:latest
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - $ASSETS_PATH_ON_HOST:$ASSETS_PATH_IN_CONTAINER:ro
    command: ["--workers", $WORKER_NUMBER]
    runtime: nvidia